---
  - name : Install and config tomcat
    hosts: all
    become: yes
    vars:
      - version: 11.0.18
      - user: tomcat
      - group: tomcat   
      - project: "sample.war"
    tasks:

      - name: Check tomcat user existence
        shell: id -u {{user}}
        register: tomcat_user_check
        ignore_errors: yes  
        tags: user_check

      - name: Print tomcat user check result
        debug:
          msg: "{{ tomcat_user_check}}"
        tags: user_check
        
      - name: Create tomcat user
        user:
          name: {{user}}
          home: /opt/tomcat
          shell: /bin/false
          state: present
        tags: user_creation
        

      - name: Install java
        apt: name=openjdk-17-jdk state=present
        tags: java_installation

      - name: Download tomcat
        get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.18/bin/apache-tomcat-11.0.18.tar.gz
          dest: /tmp/apache-tomcat-{{version}}.tar.gz
        tags: tomcat_installion

      - name: Extract tomcat
        unarchive:
          src: /tmp/apache-tomcat-{{version}}.tar.gz
          dest: /opt/tomcat/
          remote_src: true # to avoid copying the file to the remote server before unarchiving
          owner: {{user}} # to avoid permission issues when starting the tomcat service
          group: {{group}}
          extra_opts:
            - --strip-components=1 # to avoid creating a subdirectory named apache-tomcat-11.0.18
        tags: tomcat_installion

      - name: Copy tomcat.service file
        copy:
          src: tomcat.service
          dest: /etc/systemd/system/tomcat.service
          owner: root
          group: root
        tags: tomcat_service

      - name: Reload systemd
        systemd:
          daemon_reload: yes

      - name: Start and enable tomcat service
        systemd:
          name: tomcat
          state: started
          enabled: yes
        tags: tomcat_service
    
      - name: Deploy sample application
        copy:
          src: dist/{{project}}
          dest: /opt/tomcat/webapps/{{project}}
          owner: {{user}}
          group: {{group}}
        tags: app_deployment
